### ISSUE TITLE
use of label and value, then updatePosition doesn't work

### ISSUE THREAD

**Issue by anyclub** [quasarframework/quasar-ui-qscroller#158]
![image](https://user-images.githubusercontent.com/19922265/109792011-08b05800-7c4e-11eb-82d5-0e8626f55ffa.png)

Add a label item to the LIST in the DEMO, and then click the item, it cannot be automatically positioned 

![image](https://user-images.githubusercontent.com/19922265/109792184-34334280-7c4e-11eb-9098-c3e59d55015c.png)

**Comment by hawkeye64** [comment]
@anyclub Thanks for the fix. I can't take it quite yet. In your image, I see that the text isn't centered. I don't see anything in your code that would have done that so I presume it's existing and I'll have to look into it.

When I look in your code, I see if the "testLabel" is clicked, the model changes and all the other ones also go to "testValue. However, if the selection is something else, and you select via mouse wheel, then none of the other models change.

I haven't time to look into this right now. If you want to fix it, that'd be great. Otherwise, it'll have to wait until I can make time (hopefully this weekend). I'll keep this open until it gets fixed. 

Again, thanks.

**Comment by anyclub** [comment]
> When I look in your code, I see if the "testLabel" is clicked, the model changes and all the other ones also go to "testValue. However, if the selection is something else, and you select via mouse wheel, then none of the other models change.

I re-read the code and did not find a similar situation 
![123](https://user-images.githubusercontent.com/19922265/109896181-78b0f380-7ccb-11eb-99d7-13d8560d11b9.gif)

However, in my code, the NO-HEADER property is turned on,
According to common sense, HEADER should display LABEL instead of VALUE.

**Comment by anyclub** [comment]
thank you for your reply

>When I look in your code, I see if the "testLabel" is clicked, the model changes and all the other ones also go to "testValue. However, if the selection is something else, and you select via mouse wheel, then none of the other models change.

Found the reason, and added the same treatment to scrollEvent
Now the scroll wheel can also trigger related events

In addition, when VALUE and LABEL exist at the same time, HEADER should be displayed as LABEL, which is also included in the PR.

**Comment by hawkeye64** [comment]
@anyclub Thanks! I'll take a look sometime today. I appreciate your efforts.

**Comment by hawkeye64** [comment]
Fixed in v1.1.1
